version: "3.8"
services:

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - 6379:6379

  keycloak:
    image: thomasvitale/keycloak-m1:15.0.1 # Use jboss/keycloak:15.0.1 on Intel processors
    container_name: "keycloak"
    volumes:
      - ./platform/keycloak:/opt/jboss/keycloak/imports
    environment:
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    ports:
      - 8080:8080
