server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: book-route
          uri: http://localhost:8000
          predicates:
            - Path=/books/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: edge-service
            client-secret: polar-keycloak-secret
            scopes: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/PolarBookshop
  session:
    store-type: redis
